services:
  api:
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4  # sin --reload
    environment:
      LOG_LEVEL: info

  collector:
    command: celery -A tasks worker --loglevel=info --concurrency=4       # sin watchmedo
