services:
  db:
    ports:
      - "5433:5432"
  redis:
    ports:
      - "6378:6379"
  api:
    image: juaquicar/agis-orchestrator-olt-api:latest   # ya publicado en Docker Hub / GHCR
    volumes:                                     
      - ./collector/config:/config:ro
    environment:
      - OLT_CONFIG_PATH=/config/olts.yaml
    ports:
      - "8000:8000"        # opcional si expones directamente, o bien reenvías sólo desde nginx
  collector:
    image: juaquicar/agis-orchestrator-olt-collector:latest
    volumes:
      - ./collector/config:/config:ro
    environment:
      - OLT_CONFIG_PATH=/config/olts.yaml
  nginx:
    ports:
      - "8888:80"
    # puedes quitar el mapping 8888:80, sólo queda 80:80
